namespace ZawSQL.Tests.Unit;

public class ReadOnlyGuardTests
{
    [Theory]
    [InlineData("SELECT 1")]
    [InlineData("select * from t where a = 'x'")]
    [InlineData("SELECT REPLACE('a','a','b'), INSERT('abc',1,1,'x'), TRUNCATE(1.55,1)")]
    [InlineData("SHOW CREATE TABLE customers")]
    [InlineData("SHOW TABLES")]
    [InlineData("DESCRIBE customers")]
    [InlineData("DESC customers")]
    [InlineData("EXPLAIN SELECT * FROM customers")]
    [InlineData("(SELECT 1) UNION (SELECT 2)")]
    [InlineData("WITH x AS (SELECT 1 AS a) SELECT * FROM x")]
    [InlineData("TABLE customers")]
    [InlineData("SELECT * FROM t FOR UPDATE")]
    [InlineData("SELECT 'DROP TABLE logs; DELETE FROM x' AS s")]
    [InlineData("-- delete later\nSELECT 1")]
    [InlineData("/* update */ SELECT 2")]
    [InlineData("USE other")]
    [InlineData("SELECT `update` FROM (SELECT 1 AS `update`) t")]
    public void Allows_read_statements(string sql) => Assert.Null(ReadOnlyGuard.Check(sql));

    [Theory]
    [InlineData("UPDATE customers SET name='x'")]
    [InlineData("DELETE FROM logs")]
    [InlineData("INSERT INTO logs VALUES (1)")]
    [InlineData("REPLACE INTO logs VALUES (1)")]
    [InlineData("DROP TABLE logs")]
    [InlineData("CREATE TABLE t2 (id INT)")]
    [InlineData("ALTER TABLE logs ADD c INT")]
    [InlineData("TRUNCATE TABLE logs")]
    [InlineData("RENAME TABLE a TO b")]
    [InlineData("SET SESSION TRANSACTION READ WRITE")]
    [InlineData("SET @a = 1")]
    [InlineData("START TRANSACTION READ WRITE")]
    [InlineData("COMMIT")]
    [InlineData("CALL p(1)")]
    [InlineData("/*!40101 DROP TABLE logs */")]
    [InlineData("SELECT 1; DROP TABLE logs")]
    [InlineData("WITH c AS (SELECT 1) DELETE FROM logs")]
    [InlineData("SELECT * FROM logs INTO OUTFILE '/tmp/x'")]
    [InlineData("EXPLAIN ANALYZE DELETE FROM logs")]
    [InlineData("LOCK TABLES logs READ")]
    [InlineData("GRANT SELECT ON *.* TO 'u'@'%'")]
    [InlineData("DO SLEEP(0)")]
    [InlineData("KILL 1")]
    [InlineData("PREPARE s FROM 'DELETE FROM logs'")]
    public void Blocks_everything_else(string sql) => Assert.NotNull(ReadOnlyGuard.Check(sql));
}
